### ISSUE TITLE
Support for specifying file types

### ISSUE THREAD

**Issue by clubside** [anteprimorac/vscode-html-end-tag-labels#769]
**Is your feature request related to a problem? Please describe.**
I mainatin a number of Classic ASP sites. Classic ASP is just HTML with code blocks. I'd like to be able to take advantage of your plugin when editing `.asp` files.

**Describe the solution you'd like**
A field where we could include a delimited list of file extensions the plugin would use to know when to be enabled.

**Describe alternatives you've considered**
I haven't looked. Are there similar plugins to yours?

**Comment by clubside** [comment]
I found out what my problem is, your plugin actually works on `.asp` files as VSCode reports them as HTML but if there are code blocks in between elements the plugin doesn't understand that so it stops working on elements that open before the code block and close after it. I could provide a sample but it may be too niche to bother implementing.

**Comment by anteprimorac** [comment]
@clubside, thank you for reporting the issue. I can't implement and maintain support for all file formats that could have HTML in them because, for each file format, we need a parser. My mistake was allowing this extension to activate on all these file extensions. I will remove all of them that require additional parsers. If you want support for ASP files then you can make a PR and I would happily merge it if it does not add tons of additional maintenance.
